# Substitution variables used through the codebase
substitutions:
  text_font: roboto18
  text_color: black
  bg_color: white
  button_on_color: "ep_orange"
  button_off_color: "very_dark_gray"
  icon_on_color: "yellow"
  icon_off_color: "gray"
  label_on_color: "white"
  label_off_color: "gray"
  button_text_color: "white"
  button_height_single: '109px'
  button_height_double: '228px'
  button_width: '150px'
  touchscreen_idle_timeout: "30s"
  touchscreen_daytime_brightness: "100%"
  touchscreen_nighttime_brightness: "50%"
  # Boot screen configuration
  boot_screen_delay: 60s

  # Set Night mode  at Mightnight
  screen_night_hour: '0'
  screen_night_minute: '0'

  # Set Day mode at 5:30am
  screen_day_hour: '5'
  screen_day_minute: '30'
  # Screen Size
  screen_height: '272px'
  screen_width: '480px'
  sdl_height: '272'
  sdl_width: '480'



esphome:
  name: squarelinetest
  friendly_name: "SquarelineToEsphome"

host:
  mac_address: "62:23:45:AF:B3:05"
  
api:  
  
script:
  - id: time_update
    then:
      - lvgl.label.update:
          id: date_label
          text: !lambda |- # Month Day
            auto time = id(system_time).now();
            int day = time.day_of_month;
            char strftime_buf[64];
            snprintf(strftime_buf, sizeof(strftime_buf), "%s %d", time.strftime("%B").c_str(), day);
            return {strftime_buf};
      - lvgl.label.update:
          id: time_label
          text: !lambda 'return id(system_time).now().strftime("%l:%M");'

packages:
  # Generic configuration for ESP32 screens
  # wifi: !include esphome-modular-lvgl-buttons/modules/base/wifi.yaml
  colors: !include esphome-modular-lvgl-buttons/modules/base/color.yaml
  time: !include esphome-modular-lvgl-buttons/modules/base/time_homeassistant.yaml
  sensors: !include esphome-modular-lvgl-buttons/modules/sensors/sensors_base-SDL.yaml
  theme_style: !include esphome-modular-lvgl-buttons/modules/base/theme_style.yaml
  # theme_style: !include esphome-modular-lvgl-buttons/modules/base/theme_style_debug.yaml
  
  # Harware description file
  hardware: !include esphome-modular-lvgl-buttons/modules/hardware/SDL-lvgl.yaml
  
  lvgl: !include squareline_generated.yaml
  
lvgl:
# Boot screen
  top_layer: !include
    file: esphome-modular-lvgl-buttons/modules/screens/boot_screen_272x480.yaml
    vars:
      height: $screen_height
      width: $screen_width 


font:
  - file: "gfonts://Roboto" 
    id: roboto84
    size: 84
    bpp: 8
    glyphs: [ # Optomized for space
      0123456789,
      F,
      C,
      ":",
      ".",
      "°",
      "\u0025", # %
      "\u0020", # space
      "\u002C", # ,
      ]

  - file: "gfonts://Roboto"
    id: roboto48
    size: 48
    bpp: 8
    glyphs: [  # Optomized for space
      0123456789,
      F,
      C,
      ":",
      ".",
      "°",
      "\u0025", # %
      "\u0020", # space
      "\u002C", # ,
      ]  
   
  - file: "gfonts://Roboto"
    id: roboto24
    size: 24
    bpp: 8
    glyphs: [  # Optomized for space
      0123456789,
      F,
      C,
      ":",
      ".",
      "°",
      "\u0025", # %
      "\u0020", # space
      "\u002C", # ,
      ]  

  - file: "gfonts://Roboto"
    id: roboto18
    size: 18
    bpp: 8

  - file: "gfonts://Roboto"
    id: roboto14
    size: 14
    bpp: 8
   

image:
  - file: https://esphome.io/_static/logo-text-on-light.svg
    id: boot_logo_20px
    resize: 100x20  # aspect ratio 5
    type: RGB565
    transparency: alpha_channel    

